### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by clzani** [alexandrovteam/LCMS#4]
Hi,
I am getting the error message bellow when running Optimus.
Any suggestion on how to solve it?
Thanks
Carlos

ERROR Python Script (1⇒1)  0:421:406  Execute failed: Traceback (most recent call last):
  File "/Applications/KNIME 3.3.2.app/Contents/Eclipse/plugins/org.knime.python_3.4.0.v201706270758/py/PythonKernel.py", line 282, in execute
    exec(source_code, _exec_env, _exec_env)
  File "<string>", line 2, in <module>
  File "/Users/zani/OptimusMiniconda/lib/python2.7/site-packages/pandas/core/frame.py", line 1958, in __getitem__
    return self._getitem_array(key)
  File "/Users/zani/OptimusMiniconda/lib/python2.7/site-packages/pandas/core/frame.py", line 2002, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/Users/zani/OptimusMiniconda/lib/python2.7/site-packages/pandas/core/indexing.py", line 1231, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "Index([True, True, False, True], dtype='object') not in index"

**Comment by iprotsyuk** [comment]
Hi Carlos,
It seems to me that your version of pandas python module is different from the one expected by Optimus. Can you please send me the output of the following command:
`/Users/zani/OptimusMiniconda/bin/pip show pandas`

**Comment by clzani** [comment]
Hi
Thanks for the reply. I installed version 0.20.3 because KNIME preferences showed a red message like this "you are using pandas version 0.19.0, system requires at least 0.20.0". So, I installed the last version.

**Comment by clzani** [comment]
continuing...the command echo:
MacZani:~ zani$ /Users/zani/OptimusMiniconda/bin/pip show pandas
Name: pandas
Version: 0.20.3
Summary: Powerful data structures for data analysis, time series,and statistics
Home-page: http://pandas.pydata.org
Author: The PyData Development Team
Author-email: pydata@googlegroups.com
License: BSD
Location: /Users/zani/OptimusMiniconda/lib/python2.7/site-packages
Requires: python-dateutil, pytz, numpy
MacZani:~ zani$

**Comment by iprotsyuk** [comment]
Alright @clzani, I presume you're using the latest KNIME version, 3.4. If this is the case, there may be some compatibility issues with other packages required by Optimus. It hasn't been tested yet with the latest KNIME. In order to get Optimus running, I'd suggest you going to https://www.knime.com/download-previous-versions and download KNIME 3.3.3 from there.

On a side note, the error you're getting is occurring during PCA plot generation, so if you don't need PCA, you can still use other types of output that Optimus produces.

**Comment by clzani** [comment]
Thanks Ivan, I will try.
Are you considering to deploy a virtual machine (e.g. VirtualBox) with the installed Trinity platform, using for example https://github.com/NLeSC/Chemical-Analytics-Platform?

**Comment by iprotsyuk** [comment]
Hi Carlos,
It definitely sounds interesting, and at some point, we did consider VMs as a convenient way to distribute Optimus. However, the most of current and prospect users of Optimus are working on Windows operating systems, because it's the only way to run the majority of software essential for mass spectrometry. However, as far as I understand, there're certain legal issues with putting Windows-based VMs in public access. I'd be happy to learn about workarounds for that.
On the other hand, publishing Optimus within a Linux-based VM isn't likely to increase the usability of Optimus for its users, since most of them don't have experience with Linux and not handy with terminal. So in the end the idea of using VMs waned, but I'm open to suggestions on that.

**Comment by clzani** [comment]
Dear Ivan,
you mentioned in a previous message that "On a side note, the error you're getting is occurring during PCA plot generation, so if you don't need PCA, you can still use other types of output that Optimus produces."
How can I access these outputs? I tried by right-clicking on the nodes but there is no table. Is there a way to access the URI address that appears on them?

**Comment by iprotsyuk** [comment]
Hi Carlos,
By other outputs, I meant files produced by "Output Folder" and "CSV Writer" nodes. The latter one can be used only if you're going to map your samples onto image or a 3D model. Also, you can check out the feature heat map produced by the corresponding node (right click on the node -> "Interactive view: Generic Javascript View"), and save it as image, if needed.

**Comment by iprotsyuk** [comment]
@clzani, I'm closing the issue for the time being. Feel free to reopen it if the problem happens again
