### ISSUE TITLE
examples file

### ISSUE THREAD

**Issue by jeep3** [alexandrovteam/LCMS#6]
Hi iprotsyuk
I have a question to consult you. when i study the video of GNPS Trinity workflow(https://www.youtube.com/watch?v=zDcY7iuvyQY&t=4s), The Optimus workflow contain some examples file in this video. However, I can not to find corresponding file in the new version of Optimus(https://github.com/MolecularCartography/Optimus#knime-basics), such as, groupmapping file and stub.txt.Could you give me this information? Thanks a lot.

huali

**Comment by iprotsyuk** [comment]
Hi @jeep3,

- "stub.txt" is just an empty file. Its name is a key-word meaning that no input is provided to a KNIME node. It's definitely a counter-intuitive part of Optimus usage, but unfortunately, KNIME doesn't allow a workflow to run in case any "Input File" node has an empty input. That's why such a placeholder filename is being used.
- groupmapping file contains associations between sample files names and study groups (e.g. treated/untreated or anything else) they belong to. The usage of such a file may be convenient for advanced GNPS users who can generate it with some GNPS tools. However, if you want to specify study groups in Optimus, you can simply put group identifiers (again e.g. "treated" and "untreated") into the 3rd column of the experimental design spreadsheet. Note that using study groups is not obligatory, and you can run Optimus without it. The information about study groups enables advanced filtering of LC-MS features, but, again, it's not crucial. Since you're just getting started with Optimus, I'd suggest just using the stub file for the groupmapping input.

Let me know if anything isn't clear.

**Comment by iprotsyuk** [comment]
Btw, we've recently got a paper on Optimus accepted to Nature Protocols. It should be out pretty soon. The paper contains references and explanation of all parameters and input files. I'll keep you posted once it's available.

**Comment by jeep3** [comment]
OK,thank you.

**Comment by jeep3** [comment]
Hi，@iprotsyuk you paper have accepted, so, Just Accepted Manuscripts(For example, the ACS analytical chemistry) can be download?

**Comment by iprotsyuk** [comment]
@jeep3, no, unfortunately, it's not available since I haven't got final proofs yet from the journal. I'll let you know once the paper appears online in any capacity.

**Comment by iprotsyuk** [comment]
@jeep3, sorry for such a delayed response, but our Optimus paper was out a few months ago. Here it is: https://www.nature.com/articles/nprot.2017.122

I'm closing the issue for the time being. Feel free to reopen if you have any questions
